// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVGv46dL7QrSj8oGBEWyc5pUFhxosmrw',
    appId: '1:281280678662:web:34e77830fce1286420ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    authDomain: 'e-bike-511f2.firebaseapp.com',
    storageBucket: 'e-bike-511f2.appspot.com',
    measurementId: 'G-1PMFT3D6SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQK0-vT9mhg_GOgTzxiRTc5iWEDxcLeY',
    appId: '1:281280678662:android:c44d17e3d5a2348720ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    storageBucket: 'e-bike-511f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFnqHKxB3gcPhYTGqzqBxL1eFKvyBONc',
    appId: '1:281280678662:ios:a3daded4accabac420ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    storageBucket: 'e-bike-511f2.appspot.com',
    iosClientId: '281280678662-dms0s26era6a2fp1hpjiichjva17ld5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFnqHKxB3gcPhYTGqzqBxL1eFKvyBONc',
    appId: '1:281280678662:ios:a3daded4accabac420ec87',
    messagingSenderId: '281280678662',
    projectId: 'e-bike-511f2',
    storageBucket: 'e-bike-511f2.appspot.com',
    iosClientId: '281280678662-dms0s26era6a2fp1hpjiichjva17ld5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBike',
  );
}
